### ISSUE TITLE
Errata is shown as "preprint of" 

### ISSUE THREAD

**Issue by fnielsen** [WDscholia/scholia#1886] opened 2022-02-23 21:29 UTC
**Describe the bug**
Errata is shown as "preprint of"  at least for this example: https://scholia.toolforge.org/work/Q100515601

**To Reproduce**
1. Go to https://scholia.toolforge.org/work/Q100515601
2. Look in datatable

**Expected behavior**
Should not show "preprint of"

**Comment by carlinmack** [comment] 2022-03-03 22:35
duplicate of #1597

**Comment by egonw** [comment] 2022-12-29 18:32
Similar problem for retraction notices:

![image](https://user-images.githubusercontent.com/26721/209994591-136a2000-c139-4b62-af4e-0b6264396c07.png)

**Closed** 2023-02-27 18:06 UTC
Labels: bug
